config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :find_flats, only: [:show, :edit, :update, :destroy]

  def index
    @flats = Flat.all
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(id: @flat['id'])
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def find_flats
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :number_of_guests, :price_per_night, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<div class="form py-4 border-bottom mb-4">
  <%= simple_form_for(@flat) do |f| %>

    <div class="form-group">
      <%= f.input :name %>
    </div>

    <div class="form-group">
      <%= f.input :address %>
    </div>

    <div class="form-group">
      <%= f.input :description %>
    </div>

    <div class="form-group">
      <%= f.input :number_of_guests %>
    </div>

    <div class="form-group">
      <%= f.input :price_per_night %>
    </div>

    <%= f.submit class: 'btn btn-info'%>
  <% end %>
</div>

app/views/flats/index.html.erb
<div class="container">
  <div class="title">
    <h1>Flats</h1>
  </div>
  <div class="cards d-flex justify-content-between align-items-start">
    <div class="row">
      <% @flats.each do |flat| %>
        <div class="flat-card border shadow-sm m-3">
          <div class="img-card">
            <img src="https://source.unsplash.com/random" alt="flats" width="100%" height="200px">
          </div>
          <div class="card-info p-3">
            <h4><%= flat.name %></h4>
            <p><%= flat.address %></p>
          </div>
          <div class="card-flat-details d-flex px-3 border-bottom">
            <p class="mr-3"><i class="fas fa-user-friends">&nbsp</i><%= flat.number_of_guests %></p>
            <p><i class="fas fa-pound-sign">&nbsp</i><%= flat.price_per_night %></p>
          </div>
          <div class="card-flat-actions p-3">
            <%= link_to raw("<span class='text-primary'>More info</span>"), flat_path(id: flat['id']) %>
            <%= link_to raw("<span class='text-warning'>Edit</span>"), flat_path(id: flat['id']) %>
            <%= link_to raw("<span class='text-danger'>Remove</span>"), flat_path(id: flat['id']) %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container">
  <h1 class="my-3">New flat</h1>
  <%= render 'form', flat: @flat %>
  <%= link_to "Back", flats_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class="header d-flex justify-content-between align-items-center p-3">
      <h5>Simple Airbnb</h5>
      <div class="actions d-flex">
<!--         <div class="form">
          <form action="#">
            <input type="text" placeholder="search">
            <input type="submit" value="Search" class="btn btn-outline-success">
          </form>
        </div> -->
        <div class="add_flat btn btn-outline-primary ml-1">
          <%= link_to "Add flat", new_flat_path %>
        </div>
      </div>
    </div>
    <%= yield %>
  </body>
</html>